try

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -86,45 +86,45 @@ jobs:
           ./docker_clean.sh "${{ secrets.DOCKER_USERNAME }}" "${{ secrets.DOCKER_DELETE }}"
      
 
-      - name: Test
-        run: |
-          cat > .env << "ENV"  # Double quotes for expansion
-          MYSQL_HOST=${{ secrets.MYSQL_HOST }}
-          MYSQL_USER=${{ secrets.MYSQL_USER }}
-          MYSQL_PASSWORD=${{ secrets.SQL_PASS }}
-          MYSQL_DB=${{ secrets.MYSQL_DB }}
-          PORT=${{ secrets.PORT }}
-          ENV
-          GITHUB_RUN_NUMBER=${{ github.run_number }}
-          chmod +x tag_culc.sh
-          result=$(./tag_culc.sh "$GITHUB_RUN_NUMBER")
-          echo $result
-          sed -i "s|flaskaws:[0-9]\+\.[0-9]\+\.[0-9]\+|flaskaws:$result|" docker-compose.yml
+      # - name: Test
+      #   run: |
+      #     cat > .env << "ENV"  # Double quotes for expansion
+      #     MYSQL_HOST=${{ secrets.MYSQL_HOST }}
+      #     MYSQL_USER=${{ secrets.MYSQL_USER }}
+      #     MYSQL_PASSWORD=${{ secrets.SQL_PASS }}
+      #     MYSQL_DB=${{ secrets.MYSQL_DB }}
+      #     PORT=${{ secrets.PORT }}
+      #     ENV
+      #     GITHUB_RUN_NUMBER=${{ github.run_number }}
+      #     chmod +x tag_culc.sh
+      #     result=$(./tag_culc.sh "$GITHUB_RUN_NUMBER")
+      #     echo $result
+      #     sed -i "s|flaskaws:[0-9]\+\.[0-9]\+\.[0-9]\+|flaskaws:$result|" docker-compose.yml
 
 
-          ls
-          docker images
-          docker compose up -d  # Ensure Docker Compose V2 is used
-          sleep 1
-          docker compose ps
-          sleep 30
-          i=0
-          max_attempts=5
+      #     ls
+      #     docker images
+      #     docker compose up -d  # Ensure Docker Compose V2 is used
+      #     sleep 1
+      #     docker compose ps
+      #     sleep 30
+      #     i=0
+      #     max_attempts=5
           
-          while [ $i -lt $max_attempts ]; do
-            echo "Attempt $((i + 1)) of $max_attempts..."
-            if curl -sSf http://localhost:$PORT > /dev/null; then
-              echo "Flask app is reachable."
-              exit 0
-            else
-              echo "Flask app is not reachable. Retrying in 5 seconds..."
-              sleep 5
-              i=$((i + 1))
-            fi
-          done
+      #     while [ $i -lt $max_attempts ]; do
+      #       echo "Attempt $((i + 1)) of $max_attempts..."
+      #       if curl -sSf http://localhost:$PORT > /dev/null; then
+      #         echo "Flask app is reachable."
+      #         exit 0
+      #       else
+      #         echo "Flask app is not reachable. Retrying in 5 seconds..."
+      #         sleep 5
+      #         i=$((i + 1))
+      #       fi
+      #     done
 
-          echo "Flask app failed to respond after $max_attempts attempts."
-          exit 1
+      #     echo "Flask app failed to respond after $max_attempts attempts."
+      #     exit 1
 
       - name: Authenticate with Google Cloud
         id: auth
