ok

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -76,11 +76,11 @@ jobs:
           echo "Moving hub-tool to /tmp/hub-tool..."
           mv hub-tool /tmp/hub-tool || { echo "❌ Failed to move to /tmp"; exit 1; }
 
-          echo "Updating PATH..."
-          export PATH=$PATH:/tmp  # Make sure it's in the path for this step
+          echo "Adding /tmp to PATH in the environment"
+          echo "/tmp" >> $GITHUB_PATH  # Adds /tmp to PATH for the entire job
 
           echo "Verifying installation..."
-          # which hub-tool || { echo "❌ hub-tool not found in PATH"; exit 1; }
+          which hub-tool || { echo "❌ hub-tool not found in PATH"; exit 1; }
           hub-tool --version || { echo "❌ hub-tool is not working"; exit 1; }
 
 
