try argocd again

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -73,42 +73,42 @@ jobs:
           "https://hub.docker.com/v2/repositories/$DOCKER_USERNAME/$REPO_NAME/tags/0.0.0.$DELETE_IMAGE"
      
 
-      - name: Test
-        run: |
-          cat > .env << "ENV"  # Double quotes for expansion
-          MYSQL_HOST=mysql
-          MYSQL_USER=root
-          MYSQL_PASSWORD=${{ secrets.SQL_PASS }}
-          MYSQL_DB=mydb
-          PORT=5002
-          ENV
-          GITHUB_RUN_NUMBER=${{ github.run_number }}
-          sed -i "s/flaskaws:0.0.0\.[0-9]\+/flaskaws:0.0.0.$GITHUB_RUN_NUMBER/" docker-compose.yml
+      # - name: Test
+      #   run: |
+      #     cat > .env << "ENV"  # Double quotes for expansion
+      #     MYSQL_HOST=mysql
+      #     MYSQL_USER=root
+      #     MYSQL_PASSWORD=${{ secrets.SQL_PASS }}
+      #     MYSQL_DB=mydb
+      #     PORT=5002
+      #     ENV
+      #     GITHUB_RUN_NUMBER=${{ github.run_number }}
+      #     sed -i "s/flaskaws:0.0.0\.[0-9]\+/flaskaws:0.0.0.$GITHUB_RUN_NUMBER/" docker-compose.yml
 
 
-          ls
-          docker images
-          docker compose up -d  # Ensure Docker Compose V2 is used
-          sleep 1
-          docker compose ps
-          sleep 30
-          i=0
-          max_attempts=5
+      #     ls
+      #     docker images
+      #     docker compose up -d  # Ensure Docker Compose V2 is used
+      #     sleep 1
+      #     docker compose ps
+      #     sleep 30
+      #     i=0
+      #     max_attempts=5
           
-          while [ $i -lt $max_attempts ]; do
-            echo "Attempt $((i + 1)) of $max_attempts..."
-            if curl -sSf http://localhost:5002 > /dev/null; then
-              echo "Flask app is reachable."
-              exit 0
-            else
-              echo "Flask app is not reachable. Retrying in 5 seconds..."
-              sleep 5
-              i=$((i + 1))
-            fi
-          done
+      #     while [ $i -lt $max_attempts ]; do
+      #       echo "Attempt $((i + 1)) of $max_attempts..."
+      #       if curl -sSf http://localhost:5002 > /dev/null; then
+      #         echo "Flask app is reachable."
+      #         exit 0
+      #       else
+      #         echo "Flask app is not reachable. Retrying in 5 seconds..."
+      #         sleep 5
+      #         i=$((i + 1))
+      #       fi
+      #     done
 
-          echo "Flask app failed to respond after $max_attempts attempts."
-          exit 1
+      #     echo "Flask app failed to respond after $max_attempts attempts."
+      #     exit 1
 
       - name: Authenticate with Google Cloud
         id: auth
@@ -333,7 +333,7 @@ jobs:
       - name: apply argocd 
         run: |
           cd argocd
-          kubectl apply -f argocd/argo-app.yaml
+          kubectl apply -f argo-app.yaml
       # - name: Add Prometheus & Grafana Helm Repo (for ArgoCD to use)
       #   run: |
       #     helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
@@ -343,5 +343,5 @@ jobs:
       - name: Apply Monitoring App with kubectl
         run: |
           cd argocd
-          kubectl apply -f argocd/argocd_prometheus.yml
-          kubectl apply -f argocd/argocd_grafana.yml
+          kubectl apply -f argocd_prometheus.yml
+          kubectl apply -f argocd_grafana.yml
